# generated by next_commands.py on the ledger's READY list.
# Every unit re-measures after it runs. If the ledger status
# does not move, the loop STOPS - a step that reports success
# without changing anything is the failure this project keeps
# finding, and it should halt a driver, not be counted by one.
$ErrorActionPreference = 'Continue'
$done = 0

Write-Host ''
Write-Host '--- 1/25  SP_4214_Pataal_Khanda_from_Padma_Puran_1895_-_Sri_Venkateshwar_Press  morph  (15111 rows, free)'
$before = (& python scripts/next_commands.py --db "data/context.db" --verify SP_4214_Pataal_Khanda_from_Padma_Puran_1895_-_Sri_Venkateshwar_Press:morph)
python scripts/ling_kosha.py --db data/context.db --doc SP_4214_Pataal_Khanda_from_Padma_Puran_1895_-_Sri_Venkateshwar_Press --commit
if ($LASTEXITCODE -ne 0) { Write-Host '  STOP: command failed'; exit 1 }
& python scripts/automaton.py --db "data/context.db" --backfill | Out-Null
$after = (& python scripts/next_commands.py --db "data/context.db" --verify SP_4214_Pataal_Khanda_from_Padma_Puran_1895_-_Sri_Venkateshwar_Press:morph)
Write-Host ('  ledger: ' + $before + ' -> ' + $after)
if ($before -eq $after) { Write-Host '  STOP: the ledger did not move.'; exit 2 }
$done++

Write-Host ''
Write-Host '--- 2/25  MBh01  morph  (6957 rows, free)'
$before = (& python scripts/next_commands.py --db "data/context.db" --verify MBh01:morph)
python scripts/ling_kosha.py --db data/context.db --doc MBh01 --commit
if ($LASTEXITCODE -ne 0) { Write-Host '  STOP: command failed'; exit 1 }
& python scripts/automaton.py --db "data/context.db" --backfill | Out-Null
$after = (& python scripts/next_commands.py --db "data/context.db" --verify MBh01:morph)
Write-Host ('  ledger: ' + $before + ' -> ' + $after)
if ($before -eq $after) { Write-Host '  STOP: the ledger did not move.'; exit 2 }
$done++

Write-Host ''
Write-Host '--- 3/25  2015_368408_Natyasastra-With  morph  (2916 rows, free)'
$before = (& python scripts/next_commands.py --db "data/context.db" --verify 2015_368408_Natyasastra-With:morph)
python scripts/ling_kosha.py --db data/context.db --doc 2015_368408_Natyasastra-With --commit
if ($LASTEXITCODE -ne 0) { Write-Host '  STOP: command failed'; exit 1 }
& python scripts/automaton.py --db "data/context.db" --backfill | Out-Null
$after = (& python scripts/next_commands.py --db "data/context.db" --verify 2015_368408_Natyasastra-With:morph)
Write-Host ('  ledger: ' + $before + ' -> ' + $after)
if ($before -eq $after) { Write-Host '  STOP: the ledger did not move.'; exit 2 }
$done++

Write-Host ''
Write-Host '--- 4/25  smriti_14manu_smriti_seg  morph  (2568 rows, free)'
$before = (& python scripts/next_commands.py --db "data/context.db" --verify smriti_14manu_smriti_seg:morph)
python scripts/ling_kosha.py --db data/context.db --doc smriti_14manu_smriti_seg --commit
if ($LASTEXITCODE -ne 0) { Write-Host '  STOP: command failed'; exit 1 }
& python scripts/automaton.py --db "data/context.db" --backfill | Out-Null
$after = (& python scripts/next_commands.py --db "data/context.db" --verify smriti_14manu_smriti_seg:morph)
Write-Host ('  ledger: ' + $before + ' -> ' + $after)
if ($before -eq $after) { Write-Host '  STOP: the ledger did not move.'; exit 2 }
$done++

Write-Host ''
Write-Host '--- 5/25  smriti_16harita_smriti_seg  morph  (2477 rows, free)'
$before = (& python scripts/next_commands.py --db "data/context.db" --verify smriti_16harita_smriti_seg:morph)
python scripts/ling_kosha.py --db data/context.db --doc smriti_16harita_smriti_seg --commit
if ($LASTEXITCODE -ne 0) { Write-Host '  STOP: command failed'; exit 1 }
& python scripts/automaton.py --db "data/context.db" --backfill | Out-Null
$after = (& python scripts/next_commands.py --db "data/context.db" --verify smriti_16harita_smriti_seg:morph)
Write-Host ('  ledger: ' + $before + ' -> ' + $after)
if ($before -eq $after) { Write-Host '  STOP: the ledger did not move.'; exit 2 }
$done++

Write-Host ''
Write-Host '--- 6/25  2015_405693_Shatpath-Brahmanam  morph  (2259 rows, free)'
$before = (& python scripts/next_commands.py --db "data/context.db" --verify 2015_405693_Shatpath-Brahmanam:morph)
python scripts/ling_kosha.py --db data/context.db --doc 2015_405693_Shatpath-Brahmanam --commit
if ($LASTEXITCODE -ne 0) { Write-Host '  STOP: command failed'; exit 1 }
& python scripts/automaton.py --db "data/context.db" --backfill | Out-Null
$after = (& python scripts/next_commands.py --db "data/context.db" --verify 2015_405693_Shatpath-Brahmanam:morph)
Write-Host ('  ledger: ' + $before + ' -> ' + $after)
if ($before -eq $after) { Write-Host '  STOP: the ledger did not move.'; exit 2 }
$done++

Write-Host ''
Write-Host '--- 7/25  Karan_Aagama_by_Prof_Rama_Chandra_Pandey_4_-_Shaiva_Bharati_Varanasi  morph  (2084 rows, free)'
$before = (& python scripts/next_commands.py --db "data/context.db" --verify Karan_Aagama_by_Prof_Rama_Chandra_Pandey_4_-_Shaiva_Bharati_Varanasi:morph)
python scripts/ling_kosha.py --db data/context.db --doc Karan_Aagama_by_Prof_Rama_Chandra_Pandey_4_-_Shaiva_Bharati_Varanasi --commit
if ($LASTEXITCODE -ne 0) { Write-Host '  STOP: command failed'; exit 1 }
& python scripts/automaton.py --db "data/context.db" --backfill | Out-Null
$after = (& python scripts/next_commands.py --db "data/context.db" --verify Karan_Aagama_by_Prof_Rama_Chandra_Pandey_4_-_Shaiva_Bharati_Varanasi:morph)
Write-Host ('  ledger: ' + $before + ' -> ' + $after)
if ($before -eq $after) { Write-Host '  STOP: the ledger did not move.'; exit 2 }
$done++

Write-Host ''
Write-Host '--- 8/25  nirukta  morph  (2044 rows, free)'
$before = (& python scripts/next_commands.py --db "data/context.db" --verify nirukta:morph)
python scripts/ling_kosha.py --db data/context.db --doc nirukta --commit
if ($LASTEXITCODE -ne 0) { Write-Host '  STOP: command failed'; exit 1 }
& python scripts/automaton.py --db "data/context.db" --backfill | Out-Null
$after = (& python scripts/next_commands.py --db "data/context.db" --verify nirukta:morph)
Write-Host ('  ledger: ' + $before + ' -> ' + $after)
if ($before -eq $after) { Write-Host '  STOP: the ledger did not move.'; exit 2 }
$done++

Write-Host ''
Write-Host '--- 9/25  tantric_texts_series_edited_by_arthur_av  morph  (1859 rows, free)'
$before = (& python scripts/next_commands.py --db "data/context.db" --verify tantric_texts_series_edited_by_arthur_av:morph)
python scripts/ling_kosha.py --db data/context.db --doc tantric_texts_series_edited_by_arthur_av --commit
if ($LASTEXITCODE -ne 0) { Write-Host '  STOP: command failed'; exit 1 }
& python scripts/automaton.py --db "data/context.db" --backfill | Out-Null
$after = (& python scripts/next_commands.py --db "data/context.db" --verify tantric_texts_series_edited_by_arthur_av:morph)
Write-Host ('  ledger: ' + $before + ' -> ' + $after)
if ($before -eq $after) { Write-Host '  STOP: the ledger did not move.'; exit 2 }
$done++

Write-Host ''
Write-Host '--- 10/25  nilamata_seg  morph  (1400 rows, free)'
$before = (& python scripts/next_commands.py --db "data/context.db" --verify nilamata_seg:morph)
python scripts/ling_kosha.py --db data/context.db --doc nilamata_seg --commit
if ($LASTEXITCODE -ne 0) { Write-Host '  STOP: command failed'; exit 1 }
& python scripts/automaton.py --db "data/context.db" --backfill | Out-Null
$after = (& python scripts/next_commands.py --db "data/context.db" --verify nilamata_seg:morph)
Write-Host ('  ledger: ' + $before + ' -> ' + $after)
if ($before -eq $after) { Write-Host '  STOP: the ledger did not move.'; exit 2 }
$done++

Write-Host ''
Write-Host '--- 11/25  HAYASHIRSHA_PANCARATRA  morph  (1362 rows, free)'
$before = (& python scripts/next_commands.py --db "data/context.db" --verify HAYASHIRSHA_PANCARATRA:morph)
python scripts/ling_kosha.py --db data/context.db --doc HAYASHIRSHA_PANCARATRA --commit
if ($LASTEXITCODE -ne 0) { Write-Host '  STOP: command failed'; exit 1 }
& python scripts/automaton.py --db "data/context.db" --backfill | Out-Null
$after = (& python scripts/next_commands.py --db "data/context.db" --verify HAYASHIRSHA_PANCARATRA:morph)
Write-Host ('  ledger: ' + $before + ' -> ' + $after)
if ($before -eq $after) { Write-Host '  STOP: the ledger did not move.'; exit 2 }
$done++

Write-Host ''
Write-Host '--- 12/25  yajur_veda_shukla_yajur_veda  morph  (1223 rows, free)'
$before = (& python scripts/next_commands.py --db "data/context.db" --verify yajur_veda_shukla_yajur_veda:morph)
python scripts/ling_kosha.py --db data/context.db --doc yajur_veda_shukla_yajur_veda --commit
if ($LASTEXITCODE -ne 0) { Write-Host '  STOP: command failed'; exit 1 }
& python scripts/automaton.py --db "data/context.db" --backfill | Out-Null
$after = (& python scripts/next_commands.py --db "data/context.db" --verify yajur_veda_shukla_yajur_veda:morph)
Write-Host ('  ledger: ' + $before + ' -> ' + $after)
if ($before -eq $after) { Write-Host '  STOP: the ledger did not move.'; exit 2 }
$done++

Write-Host ''
Write-Host '--- 13/25  markandeya_purana  morph  (1212 rows, free)'
$before = (& python scripts/next_commands.py --db "data/context.db" --verify markandeya_purana:morph)
python scripts/ling_kosha.py --db data/context.db --doc markandeya_purana --commit
if ($LASTEXITCODE -ne 0) { Write-Host '  STOP: command failed'; exit 1 }
& python scripts/automaton.py --db "data/context.db" --backfill | Out-Null
$after = (& python scripts/next_commands.py --db "data/context.db" --verify markandeya_purana:morph)
Write-Host ('  ledger: ' + $before + ' -> ' + $after)
if ($before -eq $after) { Write-Host '  STOP: the ledger did not move.'; exit 2 }
$done++

Write-Host ''
Write-Host '--- 14/25  AphorismsOfSandilya  morph  (467 rows, free)'
$before = (& python scripts/next_commands.py --db "data/context.db" --verify AphorismsOfSandilya:morph)
python scripts/ling_kosha.py --db data/context.db --doc AphorismsOfSandilya --commit
if ($LASTEXITCODE -ne 0) { Write-Host '  STOP: command failed'; exit 1 }
& python scripts/automaton.py --db "data/context.db" --backfill | Out-Null
$after = (& python scripts/next_commands.py --db "data/context.db" --verify AphorismsOfSandilya:morph)
Write-Host ('  ledger: ' + $before + ' -> ' + $after)
if ($before -eq $after) { Write-Host '  STOP: the ledger did not move.'; exit 2 }
$done++

Write-Host ''
Write-Host '--- 15/25  harita_tritiya_sthanam  morph  (249 rows, free)'
$before = (& python scripts/next_commands.py --db "data/context.db" --verify harita_tritiya_sthanam:morph)
python scripts/ling_kosha.py --db data/context.db --doc harita_tritiya_sthanam --commit
if ($LASTEXITCODE -ne 0) { Write-Host '  STOP: command failed'; exit 1 }
& python scripts/automaton.py --db "data/context.db" --backfill | Out-Null
$after = (& python scripts/next_commands.py --db "data/context.db" --verify harita_tritiya_sthanam:morph)
Write-Host ('  ledger: ' + $before + ' -> ' + $after)
if ($before -eq $after) { Write-Host '  STOP: the ledger did not move.'; exit 2 }
$done++

Write-Host ''
Write-Host '--- 16/25  smriti_14manu_smriti  morph  (208 rows, free)'
$before = (& python scripts/next_commands.py --db "data/context.db" --verify smriti_14manu_smriti:morph)
python scripts/ling_kosha.py --db data/context.db --doc smriti_14manu_smriti --commit
if ($LASTEXITCODE -ne 0) { Write-Host '  STOP: command failed'; exit 1 }
& python scripts/automaton.py --db "data/context.db" --backfill | Out-Null
$after = (& python scripts/next_commands.py --db "data/context.db" --verify smriti_14manu_smriti:morph)
Write-Host ('  ledger: ' + $before + ' -> ' + $after)
if ($before -eq $after) { Write-Host '  STOP: the ledger did not move.'; exit 2 }
$done++

Write-Host ''
Write-Host '--- 17/25  harita_prathama_sthanam  morph  (112 rows, free)'
$before = (& python scripts/next_commands.py --db "data/context.db" --verify harita_prathama_sthanam:morph)
python scripts/ling_kosha.py --db data/context.db --doc harita_prathama_sthanam --commit
if ($LASTEXITCODE -ne 0) { Write-Host '  STOP: command failed'; exit 1 }
& python scripts/automaton.py --db "data/context.db" --backfill | Out-Null
$after = (& python scripts/next_commands.py --db "data/context.db" --verify harita_prathama_sthanam:morph)
Write-Host ('  ledger: ' + $before + ' -> ' + $after)
if ($before -eq $after) { Write-Host '  STOP: the ledger did not move.'; exit 2 }
$done++

Write-Host ''
Write-Host '--- 18/25  smriti_17gautama_smriti  morph  (109 rows, free)'
$before = (& python scripts/next_commands.py --db "data/context.db" --verify smriti_17gautama_smriti:morph)
python scripts/ling_kosha.py --db data/context.db --doc smriti_17gautama_smriti --commit
if ($LASTEXITCODE -ne 0) { Write-Host '  STOP: command failed'; exit 1 }
& python scripts/automaton.py --db "data/context.db" --backfill | Out-Null
$after = (& python scripts/next_commands.py --db "data/context.db" --verify smriti_17gautama_smriti:morph)
Write-Host ('  ledger: ' + $before + ' -> ' + $after)
if ($before -eq $after) { Write-Host '  STOP: the ledger did not move.'; exit 2 }
$done++

Write-Host ''
Write-Host '--- 19/25  upapurana_kapila_purana  morph  (85 rows, free)'
$before = (& python scripts/next_commands.py --db "data/context.db" --verify upapurana_kapila_purana:morph)
python scripts/ling_kosha.py --db data/context.db --doc upapurana_kapila_purana --commit
if ($LASTEXITCODE -ne 0) { Write-Host '  STOP: command failed'; exit 1 }
& python scripts/automaton.py --db "data/context.db" --backfill | Out-Null
$after = (& python scripts/next_commands.py --db "data/context.db" --verify upapurana_kapila_purana:morph)
Write-Host ('  ledger: ' + $before + ' -> ' + $after)
if ($before -eq $after) { Write-Host '  STOP: the ledger did not move.'; exit 2 }
$done++

Write-Host ''
Write-Host '--- 20/25  smriti_06yagyavalkya_smriti  morph  (82 rows, free)'
$before = (& python scripts/next_commands.py --db "data/context.db" --verify smriti_06yagyavalkya_smriti:morph)
python scripts/ling_kosha.py --db data/context.db --doc smriti_06yagyavalkya_smriti --commit
if ($LASTEXITCODE -ne 0) { Write-Host '  STOP: command failed'; exit 1 }
& python scripts/automaton.py --db "data/context.db" --backfill | Out-Null
$after = (& python scripts/next_commands.py --db "data/context.db" --verify smriti_06yagyavalkya_smriti:morph)
Write-Host ('  ledger: ' + $before + ' -> ' + $after)
if ($before -eq $after) { Write-Host '  STOP: the ledger did not move.'; exit 2 }
$done++

Write-Host ''
Write-Host '--- 21/25  jyotish_surya_siddhanta  morph  (58 rows, free)'
$before = (& python scripts/next_commands.py --db "data/context.db" --verify jyotish_surya_siddhanta:morph)
python scripts/ling_kosha.py --db data/context.db --doc jyotish_surya_siddhanta --commit
if ($LASTEXITCODE -ne 0) { Write-Host '  STOP: command failed'; exit 1 }
& python scripts/automaton.py --db "data/context.db" --backfill | Out-Null
$after = (& python scripts/next_commands.py --db "data/context.db" --verify jyotish_surya_siddhanta:morph)
Write-Host ('  ledger: ' + $before + ' -> ' + $after)
if ($before -eq $after) { Write-Host '  STOP: the ledger did not move.'; exit 2 }
$done++

Write-Host ''
Write-Host '--- 22/25  yajur_veda_taittiriya_krishna_yajur_veda  morph  (51 rows, free)'
$before = (& python scripts/next_commands.py --db "data/context.db" --verify yajur_veda_taittiriya_krishna_yajur_veda:morph)
python scripts/ling_kosha.py --db data/context.db --doc yajur_veda_taittiriya_krishna_yajur_veda --commit
if ($LASTEXITCODE -ne 0) { Write-Host '  STOP: command failed'; exit 1 }
& python scripts/automaton.py --db "data/context.db" --backfill | Out-Null
$after = (& python scripts/next_commands.py --db "data/context.db" --verify yajur_veda_taittiriya_krishna_yajur_veda:morph)
Write-Host ('  ledger: ' + $before + ' -> ' + $after)
if ($before -eq $after) { Write-Host '  STOP: the ledger did not move.'; exit 2 }
$done++

Write-Host ''
Write-Host '--- 23/25  smriti_13parashara_smriti  morph  (47 rows, free)'
$before = (& python scripts/next_commands.py --db "data/context.db" --verify smriti_13parashara_smriti:morph)
python scripts/ling_kosha.py --db data/context.db --doc smriti_13parashara_smriti --commit
if ($LASTEXITCODE -ne 0) { Write-Host '  STOP: command failed'; exit 1 }
& python scripts/automaton.py --db "data/context.db" --backfill | Out-Null
$after = (& python scripts/next_commands.py --db "data/context.db" --verify smriti_13parashara_smriti:morph)
Write-Host ('  ledger: ' + $before + ' -> ' + $after)
if ($before -eq $after) { Write-Host '  STOP: the ledger did not move.'; exit 2 }
$done++

Write-Host ''
Write-Host '--- 24/25  smriti_12katyayana_smriti  morph  (43 rows, free)'
$before = (& python scripts/next_commands.py --db "data/context.db" --verify smriti_12katyayana_smriti:morph)
python scripts/ling_kosha.py --db data/context.db --doc smriti_12katyayana_smriti --commit
if ($LASTEXITCODE -ne 0) { Write-Host '  STOP: command failed'; exit 1 }
& python scripts/automaton.py --db "data/context.db" --backfill | Out-Null
$after = (& python scripts/next_commands.py --db "data/context.db" --verify smriti_12katyayana_smriti:morph)
Write-Host ('  ledger: ' + $before + ' -> ' + $after)
if ($before -eq $after) { Write-Host '  STOP: the ledger did not move.'; exit 2 }
$done++

Write-Host ''
Write-Host '--- 25/25  vasishtha_dhanur_veda  morph  (38 rows, free)'
$before = (& python scripts/next_commands.py --db "data/context.db" --verify vasishtha_dhanur_veda:morph)
python scripts/ling_kosha.py --db data/context.db --doc vasishtha_dhanur_veda --commit
if ($LASTEXITCODE -ne 0) { Write-Host '  STOP: command failed'; exit 1 }
& python scripts/automaton.py --db "data/context.db" --backfill | Out-Null
$after = (& python scripts/next_commands.py --db "data/context.db" --verify vasishtha_dhanur_veda:morph)
Write-Host ('  ledger: ' + $before + ' -> ' + $after)
if ($before -eq $after) { Write-Host '  STOP: the ledger did not move.'; exit 2 }
$done++

Write-Host ''
Write-Host (' completed ' + $done + ' unit(s)')
