#!/usr/bin/env python3
# -*- coding: ascii -*-
"""
emit_corpus_shelf.py  (2026-10-08)  CORPUS_LIBRARY_C6_2026_10_08

The Srangam library (/corpus) shows the texts on the same shelves as the dashboard's Shelf page.
The shelves are a human-edited file here, configs/collections.json (COLLECTIONS_2026_10_04); they
are configuration, not corpus data, so they do not travel through the mirror. This script writes
them into the Srangam repository as src/data/corpusShelf.json, with, for every member, the title
the desk derives from its code (collections_cfg.derived_title) and its place in a series
(collections_cfg.series_of). Confirmed titles (configs/doc_titles.json) already reach the site
through the mirror (corpus.docs.title).

Run it when the shelves change (the Shelf page's "move to", or an edit of collections.json), then
commit the one file in Srangam.

  python scripts\\emit_corpus_shelf.py --srangam D:\\srangam-42267 --check   # is the site's copy current?
  python scripts\\emit_corpus_shelf.py --srangam D:\\srangam-42267           # write it (backup first)

Read-only on everything here; writes only that one file (LF, UTF-8), atomically.
"""
from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import os
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import collections_cfg as cc  # noqa: E402

MARK = "CORPUS_LIBRARY_C6_2026_10_08"
OUT_REL = Path("src") / "data" / "corpusShelf.json"


def canonical(cfg: dict) -> str:
    return json.dumps(cfg.get("collections", []), ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def build(cfg: dict) -> dict:
    cols = []
    books = {}
    for c in sorted(cfg.get("collections", []), key=lambda x: (x.get("order", 999), x.get("key", ""))):
        key = str(c.get("key", "")).strip()
        if not key:
            raise ValueError("a collection without a key")
        members = [str(m) for m in c.get("members", []) if str(m).strip()]
        cols.append({"key": key, "title": c.get("title") or key, "title_sa": c.get("title_sa") or "",
                     "order": int(c.get("order", 999)), "members": members})
        for m in members:
            if m in books:
                raise ValueError("%s is on two shelves" % m)
            books[m] = {"derived_title": cc.derived_title(m), "series": cc.series_of(m)}
    return {
        "_about": ("Generated by sanskrit-automatonv2/scripts/emit_corpus_shelf.py from configs/collections.json "
                   "(%s). Do not edit here: edit the shelves on the translation desk and run the script again."
                   % MARK),
        "_source_sha256": hashlib.sha256(canonical(cfg).encode("utf-8")).hexdigest(),
        "collections": cols,
        "books": dict(sorted(books.items())),
    }


def render(doc: dict) -> str:
    return json.dumps(doc, ensure_ascii=False, indent=1) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--srangam", required=True, help="the Srangam repository root, e.g. D:\\srangam-42267")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    site = Path(a.srangam)
    if not (site / "src" / "App.tsx").exists():
        print("FAIL: %s is not the Srangam repository." % site); return 2
    if not cc.CFG.exists():
        print("FAIL: %s not found." % cc.CFG); return 2
    cfg = json.loads(cc.CFG.read_text(encoding="utf-8"))
    try:
        text = render(build(cfg))
    except ValueError as e:
        print("FAIL: %s. Nothing written." % e); return 2
    out = site / OUT_REL
    current = out.read_text(encoding="utf-8").replace("\r\n", "\n") if out.exists() else None
    n_books = len(json.loads(text)["books"])
    if current == text:
        print("current: %s matches configs/collections.json (%d shelves, %d texts)." % (OUT_REL, len(cfg.get("collections", [])), n_books))
        return 0
    if a.check:
        print("STALE: %s %s. Run without --check to write it." % (OUT_REL, "differs" if current else "does not exist"))
        return 1
    out.parent.mkdir(parents=True, exist_ok=True)
    if out.exists():
        shutil.copy2(out, out.with_name(out.name + ".bak_shelf_" + datetime.date.today().strftime("%Y%m%d")))
    tmp = out.with_name(out.name + ".tmp_shelf")
    tmp.write_bytes(text.encode("utf-8"))
    os.replace(tmp, out)
    print("wrote %s (%d texts). Commit it in Srangam: git add %s" % (out, n_books, OUT_REL.as_posix()))
    return 0


if __name__ == "__main__":
    sys.exit(main())
