#!/usr/bin/env python3
"""patch_publish_bridge.py  (MARK PUBLISH_BRIDGE_2026_09_27)

publish_srangam.py, made runnable and usable without a service-role key:

  1  the __main__ guard sat ABOVE gate_rows() and doc_title(), so a real push
     died with NameError; it moves to the end of the file.
  2  --dry-run read doc["title"]; docs has no title column. It uses doc_title().
  3  --gate-report / --no-gate were parsed and the gate never ran. It runs now
     before every push, dry-run and SQL emit.
  4  --emit-sql DIR writes the same upserts as pasteable UTF-8 SQL files for the
     Lovable Cloud SQL editor (00_text, NN_passages, 99_verify, MANIFEST).
     Idempotent, never deletes, never changes srangam_texts.published.

  python scripts/patch_publish_bridge.py --root .           # check
  python scripts/patch_publish_bridge.py --root . --apply   # write

Backup publish_srangam.py.bak_pb_20260927; line endings preserved.
"""
import argparse, os, py_compile, shutil, sys
from pathlib import Path

MARK = 'PUBLISH_BRIDGE_2026_09_27'
EDITS = [
  ('scripts/publish_srangam.py', [
    ('main guard moves to the end (it ran before gate_rows/doc_title existed)',
     'if __name__ == "__main__":\n    main()\n\n\n# \u2500\u2500 Publication gate (PUBLISH_GATE_2026_09_06)',
     '# PUBLISH_BRIDGE_2026_09_27: the __main__ guard used to stand here, so main()\n# ran before gate_rows() and doc_title() below were defined. It is at the end.\n\n\n# \u2500\u2500 Publication gate (PUBLISH_GATE_2026_09_06)'),
    ('emit_sql + guard at the end',
     '    return " ".join(w.capitalize() if w.islower() else w for w in s.split(" "))\n',
     '    return " ".join(w.capitalize() if w.islower() else w for w in s.split(" "))\n\n\n# \u2500\u2500 SQL-editor bridge (PUBLISH_BRIDGE_2026_09_27) \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n# There is no service-role key on this machine (house rule: privileged Supabase\n# access goes through the Lovable Cloud SQL editor only), so the REST path above\n# can never run. --emit-sql writes the SAME upserts as UTF-8 SQL files, one\n# pasteable file at a time, generated by this program - never through a shell\n# redirect or the clipboard (CONSOLIDATION_PLAN section 10). Every file is\n# idempotent, never deletes, never touches srangam_texts.published, and ends\n# with a SELECT so the editor (which shows only the last result) confirms it.\n\ndef _sql_lit(v):\n    if v is None:\n        return "NULL"\n    if isinstance(v, bool):\n        return "TRUE" if v else "FALSE"\n    if isinstance(v, int):\n        return str(v)\n    if isinstance(v, float):\n        return repr(v)\n    s = str(v).replace("\\x00", "")\n    return "\'" + s.replace("\'", "\'\'") + "\'"\n\n\n_SQL_HEAD = ("-- PUBLISH_BRIDGE_2026_09_27 - generated by scripts/publish_srangam.py --emit-sql\\n"\n             "-- Paste this ONE file into the Lovable Cloud SQL editor and run it.\\n"\n             "-- Idempotent (re-running changes nothing), never deletes, never\\n"\n             "-- changes srangam_texts.published. Source: context.db, read-only.\\n")\n\n\ndef emit_sql(out_dir, doc, rows, engine, source_note, batch=200, max_bytes=450000):\n    import hashlib\n    code = doc["code"]\n    out = pathlib.Path(out_dir) / code\n    out.mkdir(parents=True, exist_ok=True)\n    for old in out.glob("*.sql"):\n        old.unlink()                        # a fresh, complete set every time\n    lit = _sql_lit\n    files = []\n\n    def write(name, body):\n        p = out / name\n        data = body.encode("utf-8")\n        p.write_bytes(data)\n        files.append((name, len(data), hashlib.sha256(data).hexdigest()))\n\n    write("00_text.sql", _SQL_HEAD +\n          "INSERT INTO public.srangam_texts (doc_code, title, category, source_note, "\n          "translation_engine, passage_count)\\nVALUES (%s, %s, %s, %s, %s, %d)\\n"\n          "ON CONFLICT (doc_code) DO UPDATE SET title = EXCLUDED.title, "\n          "category = EXCLUDED.category, source_note = EXCLUDED.source_note,\\n"\n          "  translation_engine = COALESCE(EXCLUDED.translation_engine, "\n          "public.srangam_texts.translation_engine),\\n"\n          "  passage_count = EXCLUDED.passage_count, updated_at = now();\\n"\n          "SELECT id, doc_code, passage_count, published FROM public.srangam_texts "\n          "WHERE doc_code = %s;\\n"\n          % (lit(code), lit(doc_title(code) or code), lit(doc["category"]), lit(source_note),\n             lit(engine), len(rows), lit(code)))\n\n    chunks, cur, size = [], [], 0\n    for r in rows:\n        tup = "(%s, %s, %s, %s, %s, %s, %s)" % (\n            lit(int(r["page_no"])), lit(int(r["idx"])), lit(r["text"] or ""),\n            lit(r["iast"]), lit(r["translation"]), lit(r["verse_ref"]),\n            lit(float(r["quality_score"]) if r["quality_score"] is not None else None))\n        if cur and (len(cur) >= batch or size + len(tup) > max_bytes):\n            chunks.append(cur); cur, size = [], 0\n        cur.append((r, tup)); size += len(tup)\n    if cur:\n        chunks.append(cur)\n    for n, chunk in enumerate(chunks, 1):\n        first, last = chunk[0][0], chunk[-1][0]\n        write("%02d_passages.sql" % n, _SQL_HEAD +\n              "-- passages %d of %d files: p%s.%s .. p%s.%s (%d rows)\\n"\n              % (n, len(chunks), first["page_no"], first["idx"], last["page_no"], last["idx"], len(chunk)) +\n              "INSERT INTO public.srangam_text_passages (text_id, page_no, idx, sanskrit, iast, "\n              "translation, verse_ref, quality_score)\\n"\n              "SELECT t.id, v.page_no::int, v.idx::int, v.sanskrit, v.iast::text, v.translation, "\n              "v.verse_ref::text, v.quality_score::real\\nFROM (VALUES\\n  " +\n              ",\\n  ".join(t for _r, t in chunk) +\n              "\\n) AS v(page_no, idx, sanskrit, iast, translation, verse_ref, quality_score)\\n"\n              "JOIN public.srangam_texts t ON t.doc_code = %s\\n" % lit(code) +\n              "ON CONFLICT (text_id, page_no, idx) DO UPDATE SET sanskrit = EXCLUDED.sanskrit, "\n              "iast = EXCLUDED.iast,\\n  translation = EXCLUDED.translation, "\n              "verse_ref = EXCLUDED.verse_ref, quality_score = EXCLUDED.quality_score, "\n              "updated_at = now();\\n"\n              "SELECT %d AS rows_in_this_file, count(*) AS now_on_site FROM public.srangam_text_passages p "\n              "JOIN public.srangam_texts t ON t.id = p.text_id WHERE t.doc_code = %s;\\n"\n              % (len(chunk), lit(code)))\n\n    keys = ",".join("(%d,%d)" % (int(r["page_no"]), int(r["idx"])) for r in rows)\n    write("99_verify.sql", _SQL_HEAD +\n          "-- read-only. Expect local_passages = remote_passages and no stale rows.\\n"\n          "-- A \'stale\' row is on the site but no longer in the local publishable set\\n"\n          "-- (emptied, re-split or withheld by the gate); this bridge never deletes it.\\n"\n          "WITH local_keys(page_no, idx) AS (VALUES %s)\\n"\n          "SELECT t.doc_code, %d AS local_passages, count(p.id) AS remote_passages,\\n"\n          "  count(p.id) FILTER (WHERE NOT EXISTS (SELECT 1 FROM local_keys k "\n          "WHERE k.page_no = p.page_no AND k.idx = p.idx)) AS stale_on_site,\\n"\n          "  t.published\\nFROM public.srangam_texts t LEFT JOIN public.srangam_text_passages p "\n          "ON p.text_id = t.id\\nWHERE t.doc_code = %s GROUP BY t.doc_code, t.published;\\n"\n          % (keys, len(rows), lit(code)))\n\n    man = ["PUBLISH_BRIDGE_2026_09_27 manifest for %s" % code,\n           "local publishable passages: %d  (after the publication gate)" % len(rows),\n           "paste in order; each file ends with a SELECT that confirms it:", ""]\n    man += ["  %-18s %9d bytes  sha256 %s" % f for f in files]\n    (out / "MANIFEST.txt").write_text("\\n".join(man) + "\\n", encoding="utf-8")\n    print("%s: %d passage(s) -> %d SQL file(s) in %s" % (code, len(rows), len(files), out))\n    for f in files:\n        print("  %-18s %9d bytes" % f[:2])\n    return out\n\n\nif __name__ == "__main__":\n    main()\n'),
    ('dry-run title from the code (docs has no title column)',
     "title={doc['title']!r} ",
     "title={doc_title(doc['code'])!r} "),
    ('--emit-sql arguments',
     '    ap.add_argument("--unpublish", action="store_true",\n                    help="hide the doc from the public reader")\n    args = ap.parse_args()\n',
     '    ap.add_argument("--unpublish", action="store_true",\n                    help="hide the doc from the public reader")\n    ap.add_argument("--emit-sql", default=None, metavar="DIR",\n                    help="PUBLISH_BRIDGE_2026_09_27: write the upserts as pasteable UTF-8 "\n                         "SQL files under DIR/<doc>/ for the Lovable Cloud SQL editor "\n                         "(no service-role key needed). No network use.")\n    ap.add_argument("--sql-batch", type=int, default=200,\n                    help="passages per SQL file for --emit-sql (default 200)")\n    args = ap.parse_args()\n'),
    ('the gate is applied (it was parsed and never called)',
     '    rows = translated_passages(con, doc["id"])\n    if not rows:\n        sys.exit(f"{args.doc}: no translated passages yet \u2014 nothing to push.")\n',
     '    rows = translated_passages(con, doc["id"])\n    if not rows:\n        sys.exit(f"{args.doc}: no translated passages yet \u2014 nothing to push.")\n    # PUBLISH_BRIDGE_2026_09_27: --gate-report / --no-gate were parsed and the\n    # gate never ran. It runs now, before every push, dry-run and SQL emit.\n    keep, withheld = gate_rows(rows, dup_threshold=args.dup_threshold,\n                               dup_window=args.dup_window)\n    if args.gate_report:\n        print_gate_report(args.doc, keep, withheld)\n        return\n    if not args.no_gate:\n        if withheld:\n            print(f"{args.doc}: the publication gate withholds {len(withheld)} of "\n                  f"{len(rows)} passage(s) (--gate-report shows which and why)")\n        rows = keep\n        if not rows:\n            sys.exit(f"{args.doc}: every translated passage is withheld by the gate.")\n'),
    ('emit branch before dry-run',
     '    if args.dry_run:\n        sample = rows[0]\n',
     '    if args.emit_sql:\n        emit_sql(args.emit_sql, doc, rows, args.engine, source_note, args.sql_batch)\n        return\n\n    if args.dry_run:\n        sample = rows[0]\n'),
  ]),
]

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=".")
    ap.add_argument("--apply", action="store_true")
    a = ap.parse_args()
    root = Path(a.root)
    plan, bad = [], 0
    for rel, eds in EDITS:
        p = root / rel
        if not p.exists():
            print("  MISSING  %s" % rel); bad += 1; continue
        raw = p.read_bytes()
        crlf = b"\r\n" in raw
        text = raw.decode("utf-8").replace("\r\n", "\n")
        if MARK in text:
            print("  already  %s (marker present) - skipped" % rel); continue
        new = text
        for name, old, rep in eds:
            n = new.count(old)
            if n != 1:
                print("  ANCHOR   %s :: %s matched %d time(s), need exactly 1" % (rel, name, n))
                bad += 1; continue
            new = new.replace(old, rep, 1)
            print("  ok       %s :: %s" % (rel, name))
        if MARK not in new:
            print("  ANCHOR   %s :: marker not present after edits" % rel); bad += 1
        plan.append((p, crlf, new))
    if bad:
        print("REFUSED: %d problem(s); nothing written." % bad); return 2
    if not plan:
        print("nothing to do - every file already patched."); return 0
    if not a.apply:
        print("CHECK PASSED for %d file(s). Re-run with --apply to write." % len(plan)); return 0
    for p, crlf, new in plan:
        bak = p.with_name(p.name + ".bak_pb_20260927")
        if not bak.exists():
            shutil.copy2(p, bak)
        tmp = p.with_name(p.name + ".tmp_patch")
        tmp.write_bytes((new.replace("\n", "\r\n") if crlf else new).encode("utf-8"))
        os.replace(str(tmp), str(p))   # atomic: a job starting now reads old or new, never half
        if p.suffix == ".py":
            py_compile.compile(str(p), doraise=True)
        print("  WROTE    %s  (backup %s)" % (p.name, bak.name))
    print("APPLIED. To undo: copy each .bak_pb_20260927 back over its file.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
